---

- name: build & store docker images in dockerhub
  hosts: localhost
  vars:
    DOCKER_HUB_USERNAME: <docker-username>
  tasks:

    - name: build container image for pod 1
      docker_image:
        name: "{{ DOCKER_HUB_USERNAME }}/a-pod-1"
        tag: latest
        push: yes
        build:
          path: ../flask_docker_demo
        source: build

    - name: build container image for pod 2
      docker_image:
        name: "{{ DOCKER_HUB_USERNAME }}/a-pod-2"
        tag: latest
        push: yes
        build:
          path: ../second-pod
        source: build
