---

- name: build & store docker images in dockerhub
  hosts: localhost
  vars:
    DOCKER_HUB_USERNAME: vdockerhub
  tasks:

    - name: remove container image for pod 1
      docker_image:
        name: "{{ DOCKER_HUB_USERNAME }}/a-pod-1"
        tag: latest
        state: absent

    - name: remove container image for pod 2
      docker_image:
        name: "{{ DOCKER_HUB_USERNAME }}/a-pod-2"
        tag: latest
        state: absent

    - name: build container image for pod 1
      docker_image:
        name: "{{ DOCKER_HUB_USERNAME }}/a-pod-1"
        tag: latest
        push: yes
        build:
          path: ../micro-service-A
        source: build

    - name: build container image for pod 2
      docker_image:
        name: "{{ DOCKER_HUB_USERNAME }}/a-pod-2"
        tag: latest
        push: yes
        build:
          path: ../micro-service-B
        source: build
