---

- name: deploy test pods on kubernetes
  hosts: localhost
  tasks:

    - name: create namespace
      kubernetes.core.k8s:
        name: python-pods-ns
        kind: namespace
        state: present

    - name: deploy python pod 1
      kubernetes.core.k8s:
        src: ../micro-service-A/a-pod-1-k8s.yaml
        namespace: python-pods-ns
        state: present

    - name: deploy python pod 2
      kubernetes.core.k8s:
        src: ../micro-service-B/a-pod-2-k8s.yaml
        namespace: python-pods-ns
        state: present

    - name: list the k8s objects deployed
      shell: kubectl get all -n python-pods-ns
      register: command_output

    - debug:
        var: command_output.stdout_lines
