apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-pod-2
  labels:
    app: a-pod-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a-pod-2
  template:
    metadata:
      labels:
        app: a-pod-2
    spec:
      containers:
      - name: a-pod-2
        image: vdockerhub/a-pod-2:latest
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: a-pod-2
  name: a-pod-2
spec:
  ports:
  - port: 5002
    protocol: TCP
    targetPort: 5002
  selector:
    app: a-pod-2
  type: ClusterIP
status:
  loadBalancer: {}